matrix:
  include:
    - language: node_js
      node_js:
        - 'stable'
      script:
        - npm run lint
        - npm run test
    - language: python
      python:
        - "2.7"
        - "3.6"
      script: python -m unittest discover
    # Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
    - language: python
      python: 3.7
      dist: xenial
      sudo: true
      script: python -m unittest discover
