matrix:
  include:
    - language: node_js
      node_js:
        - 'stable'
      script:
        - npm run lint
        - npm run test
    - language: python
      python:
        - "3.6"
        - "3.7"
        - "3.8"
      script: python -m unittest discover
      dist: bionic
